server:
  port: 9000
spring:
  application:
    name: bdx-backstage-manager #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.247.154:3306/bdx?characterEncoding=UTF8
    username: root
    password: bdxmysqlszwan
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 120.79.247.154
    password: bdxredisszwan
  rabbitmq:
    host: 120.79.247.154
    username: user
    password: bdxrabbitmqszwan
jwt:
  config:
    key: szwan
    ttl: 7200000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
security:
  basic:
    enabled: false
qiniuyun:
  accessKey: ExPCkduypDz-jNhbPl1uwE3dMXMXGttSr5EYCzHl
  secretKey: bEec7XyV5OCdFnsDZmIPT3n8K-UKRg_K_2pUq3OO
  bucket: bdxheadimg
